version: '3'
services:
  app:
    container_name: docker-node-mongodb
    restart: always
    build: .
    ports:
      - '5005:5005'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
